### ISSUE TITLE
plantuml.jar is not working 

### ISSUE THREAD

**Issue by jkettsjr** [Andreone/dokuwiki_plantuml#15]
When generating the following from a command line a png file is created accurately.

java -jar plantuml.jar -verbose test.txt

@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
Jeff -> Bob: Authentication Request
@enduml

When using DokuWiki  and generating the following page the text file is created in the cache but no png is created. 

dokuwiki page:
(uml)
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
Jeff -> Bob: Authentication Request
(/uml)

text page created is the same with @startuml and @enduml

Using Dokuwiki Version: Release 2013-05-10a "Weatherwax"

Render Locally = Yes
Path to Java = /usr/bin/java
Path to Plant UML jar File = /var/www/dokuwiki/lib/plugins/planuml/local/plantuml.jar
Remote url of PlantUML servlet = http://plantuml.com
Enable "New UML Graph" button in editor = Yes
Image used to draw the toolbar button = res/icon1.png

java -jar plantuml.jar -version
PlantUML version 7980 (Wed Sep 18 12:17:57 EDT 2013)
(GPL source distribution)
OpenJDK Runtime Environment
OpenJDK 64-Bit Server VM
1.6.0_24-b24
Linux

The environment variable GRAPHVIZ_DOT has not been set
Dot executable is /usr/bin/dot
Dot version: dot - graphviz version 2.26.0 (20091210.2329)
Installation seems OK. File generation OK

**Comment by izacaslo** [comment]
@jkettsjr Please, detail the modification you did to .htaccess file.

**Comment by jkettsjr** [comment]
We stopped using the product. Too many problems and no real solutions or support.



Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone


-------- Original message --------
